Setting bot-amil during github actions run
cloudposse/github-action-terraform-auto-context pull request #9
Opened 2022-05-11 18:06 UTC by dylanbannon

## what

Changing the default value of the GHA input `bot-email` to null and then setting it to the cloudpossebot defult during the GHA run if it's unset.

## why

This avoids putting a magic number into the `bot-email` default.

## References

CPCO-580

2022-05-11 18:48 UTC, dylanbannon commented
tests passed:
https://github.com/cloudposse/github-action-terraform-auto-context/runs/6393988290?check_suite_focus=true#step:3:293
https://github.com/cloudposse/github-action-terraform-auto-context/runs/6394026195?check_suite_focus=true#step:3:316

2022-05-12 02:21 UTC, osterman commented on action.yml
> +          bot_email=${bot_id}+cloudpossebot@users.noreply.github.com
```suggestion
          bot_email=${bot_id}+${{ inputs.bot-name }}@users.noreply.github.com
```

2022-05-12 02:21 UTC, osterman commented on action.yml
> +          bot_id=$(curl -sSL 'https://api.github.com/users/cloudpossebot' | jq .id)
```suggestion
          bot_id=$(curl -sSL 'https://api.github.com/users/${{ inputs.bot-name }}' | jq .id)
```

2022-05-12 02:22 UTC, osterman commented on action.yml
> +    - name: "Set bot-email to cloudpossebot default if inputs.bot-email not provided"
```suggestion
    - name: "Set bot-email to GitHub default if inputs.bot-email not provided"
```

2022-05-30 23:53 UTC, dylanbannon commented
Tests work: https://github.com/cloudposse/github-action-terraform-auto-context/actions/runs/2411836199

2022-06-07 18:18 UTC, mcalhoun requested changes
Made a few comments

2022-06-07 18:18 UTC, mcalhoun commented on .github/workflows/auto-context-reusable.yml
> +        description: "Name of branch to commit updated context.tf to"
```suggestion
        description: "Name of branch where the updated context.tf will be added"
```

2022-06-07 18:18 UTC, mcalhoun commented on .github/workflows/auto-context-reusable.yml
> +        description: "Username to write commits under"
```suggestion
        description: "GitHub username the action will use to commit code"
```

2022-06-07 18:18 UTC, mcalhoun commented on .github/workflows/auto-context-reusable.yml
> +        description: "Email to write commits under"
```suggestion
        description: "Email Address associated with the GitHub user the action will use to commit code"
```

2022-06-07 18:18 UTC, mcalhoun commented on action.yml
> +        echo $bot_email
Is this left over from testing?

2022-06-07 18:18 UTC, mcalhoun commented on context_update.sh
> +echo "HOST_REPO: ${HOST_REPO}"
Left over from testing?

2022-06-07 18:18 UTC, mcalhoun commented on context_update.sh
>  if [[ "$HOST_REPO" == "cloudposse/github-action-terraform-auto-context" ]]; then
Could use use `github.action_repository` instead of the hard-coded value?

2022-06-07 18:18 UTC, mcalhoun commented on context_update.sh
>  if [[ "$HOST_REPO" == "cloudposse/github-action-terraform-auto-context" ]]; then
Same comment as above

2022-06-14 19:50 UTC, merged